"""empty message

Revision ID: 10767c591cb9
Revises: 3baaa0643883
Create Date: 2021-11-19 15:26:55.682805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10767c591cb9'
down_revision = '3baaa0643883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('andamento', sa.Boolean(), nullable=True))
    op.add_column('tickets', sa.Column('intervalo', sa.Interval(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'intervalo')
    op.drop_column('tickets', 'andamento')
    # ### end Alembic commands ###
