"""empty message

Revision ID: 11288f035787
Revises: 387b43da569a
Create Date: 2021-11-04 13:44:47.289586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11288f035787'
down_revision = '387b43da569a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('infopublic_acessos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infopublic_acessos_email'), 'infopublic_acessos', ['email'], unique=True)
    op.create_index(op.f('ix_infopublic_acessos_username'), 'infopublic_acessos', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_infopublic_acessos_username'), table_name='infopublic_acessos')
    op.drop_index(op.f('ix_infopublic_acessos_email'), table_name='infopublic_acessos')
    op.drop_table('infopublic_acessos')
    op.drop_table('roles')
    # ### end Alembic commands ###
