"""empty message

Revision ID: 3baaa0643883
Revises: 6c328b88d06f
Create Date: 2021-11-19 14:12:09.392181

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3baaa0643883'
down_revision = '6c328b88d06f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(length=64), nullable=True),
    sa.Column('nome', sa.String(length=64), nullable=True),
    sa.Column('sobrenome', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('telefone', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_cpf'), 'usuarios', ['cpf'], unique=True)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_nome'), 'usuarios', ['nome'], unique=False)
    op.create_index(op.f('ix_usuarios_sobrenome'), 'usuarios', ['sobrenome'], unique=False)
    op.create_index(op.f('ix_usuarios_telefone'), 'usuarios', ['telefone'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fechado', sa.Boolean(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('hora', sa.Time(), nullable=True),
    sa.Column('cpf', sa.String(length=64), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.Column('sistema', sa.String(length=64), nullable=True),
    sa.Column('entidade', sa.String(length=120), nullable=True),
    sa.Column('assunto', sa.String(length=120), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_assunto'), 'tickets', ['assunto'], unique=False)
    op.create_index(op.f('ix_tickets_cpf'), 'tickets', ['cpf'], unique=True)
    op.create_index(op.f('ix_tickets_date'), 'tickets', ['date'], unique=False)
    op.create_index(op.f('ix_tickets_hora'), 'tickets', ['hora'], unique=False)
    op.create_index(op.f('ix_tickets_nome'), 'tickets', ['nome'], unique=False)
    op.create_index(op.f('ix_tickets_sistema'), 'tickets', ['sistema'], unique=False)
    op.drop_index('ix_infopublic_acessos_cpf', table_name='infopublic_acessos')
    op.drop_index('ix_infopublic_acessos_email', table_name='infopublic_acessos')
    op.drop_index('ix_infopublic_acessos_nome', table_name='infopublic_acessos')
    op.drop_index('ix_infopublic_acessos_sobrenome', table_name='infopublic_acessos')
    op.drop_index('ix_infopublic_acessos_telefone', table_name='infopublic_acessos')
    op.drop_table('infopublic_acessos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infopublic_acessos',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cpf', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('nome', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('sobrenome', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('telefone', mysql.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='infopublic_acessos_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_infopublic_acessos_telefone', 'infopublic_acessos', ['telefone'], unique=False)
    op.create_index('ix_infopublic_acessos_sobrenome', 'infopublic_acessos', ['sobrenome'], unique=False)
    op.create_index('ix_infopublic_acessos_nome', 'infopublic_acessos', ['nome'], unique=False)
    op.create_index('ix_infopublic_acessos_email', 'infopublic_acessos', ['email'], unique=True)
    op.create_index('ix_infopublic_acessos_cpf', 'infopublic_acessos', ['cpf'], unique=True)
    op.drop_index(op.f('ix_tickets_sistema'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_nome'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_hora'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_date'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_cpf'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_assunto'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_usuarios_telefone'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_sobrenome'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_nome'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_cpf'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
