"""empty message

Revision ID: 6c328b88d06f
Revises: 7a9800479355
Create Date: 2021-11-18 22:28:22.947839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c328b88d06f'
down_revision = '7a9800479355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('infopublic_acessos', sa.Column('cpf', sa.String(length=64), nullable=True))
    op.add_column('infopublic_acessos', sa.Column('nome', sa.String(length=64), nullable=True))
    op.add_column('infopublic_acessos', sa.Column('sobrenome', sa.String(length=64), nullable=True))
    op.add_column('infopublic_acessos', sa.Column('telefone', sa.String(length=64), nullable=True))
    op.drop_index('ix_infopublic_acessos_username', table_name='infopublic_acessos')
    op.create_index(op.f('ix_infopublic_acessos_cpf'), 'infopublic_acessos', ['cpf'], unique=True)
    op.create_index(op.f('ix_infopublic_acessos_nome'), 'infopublic_acessos', ['nome'], unique=False)
    op.create_index(op.f('ix_infopublic_acessos_sobrenome'), 'infopublic_acessos', ['sobrenome'], unique=False)
    op.create_index(op.f('ix_infopublic_acessos_telefone'), 'infopublic_acessos', ['telefone'], unique=False)
    op.drop_column('infopublic_acessos', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('infopublic_acessos', sa.Column('username', mysql.VARCHAR(length=64), nullable=True))
    op.drop_index(op.f('ix_infopublic_acessos_telefone'), table_name='infopublic_acessos')
    op.drop_index(op.f('ix_infopublic_acessos_sobrenome'), table_name='infopublic_acessos')
    op.drop_index(op.f('ix_infopublic_acessos_nome'), table_name='infopublic_acessos')
    op.drop_index(op.f('ix_infopublic_acessos_cpf'), table_name='infopublic_acessos')
    op.create_index('ix_infopublic_acessos_username', 'infopublic_acessos', ['username'], unique=True)
    op.drop_column('infopublic_acessos', 'telefone')
    op.drop_column('infopublic_acessos', 'sobrenome')
    op.drop_column('infopublic_acessos', 'nome')
    op.drop_column('infopublic_acessos', 'cpf')
    # ### end Alembic commands ###
