"""empty message

Revision ID: d269cd4ebacf
Revises: 4bd396567c71
Create Date: 2021-11-23 17:56:00.141610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd269cd4ebacf'
down_revision = '4bd396567c71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tickets_cpf', table_name='tickets')
    op.create_index(op.f('ix_tickets_cpf'), 'tickets', ['cpf'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_cpf'), table_name='tickets')
    op.create_index('ix_tickets_cpf', 'tickets', ['cpf'], unique=True)
    # ### end Alembic commands ###
