"""empty message

Revision ID: dc81afcac56f
Revises: 10767c591cb9
Create Date: 2021-11-22 21:14:11.202894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc81afcac56f'
down_revision = '10767c591cb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'hora',
               existing_type=mysql.TIME(),
               nullable=False)
    op.drop_index('ix_tickets_hora', table_name='tickets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tickets_hora', 'tickets', ['hora'], unique=False)
    op.alter_column('tickets', 'hora',
               existing_type=mysql.TIME(),
               nullable=True)
    # ### end Alembic commands ###
